require('user.plugins')
require('user.mappings')
require('user.options')
require('user.commands')
require('user.colorscheme')

require('user.cmp')
require('user.lsp')
require('user.treesitter')
require('user.dap')
